/**
 * Languages supported by Tesseract.js (tessdata). Ordered with English first
 * (the default), then alphabetical by language name. Codes are ISO 639-2/B
 * three-letter codes, occasionally suffixed with script or region variants
 * matching the upstream tessdata filenames.
 *
 * Source: https://github.com/tesseract-ocr/tessdata/blob/main/README.md
 */

export interface TesseractLanguage {
  value: string;
  label: string;
}

export const TESSERACT_LANGUAGES: TesseractLanguage[] = [
  { value: 'eng', label: 'English (eng)' },
  { value: 'afr', label: 'Afrikaans (afr)' },
  { value: 'sqi', label: 'Albanian (sqi)' },
  { value: 'amh', label: 'Amharic (amh)' },
  { value: 'grc', label: 'Ancient Greek (grc)' },
  { value: 'ara', label: 'Arabic (ara)' },
  { value: 'hye', label: 'Armenian (hye)' },
  { value: 'asm', label: 'Assamese (asm)' },
  { value: 'aze', label: 'Azerbaijani (aze)' },
  { value: 'aze_cyrl', label: 'Azerbaijani — Cyrillic (aze_cyrl)' },
  { value: 'eus', label: 'Basque (eus)' },
  { value: 'bel', label: 'Belarusian (bel)' },
  { value: 'ben', label: 'Bengali (ben)' },
  { value: 'bos', label: 'Bosnian (bos)' },
  { value: 'bre', label: 'Breton (bre)' },
  { value: 'bul', label: 'Bulgarian (bul)' },
  { value: 'mya', label: 'Burmese (mya)' },
  { value: 'cat', label: 'Catalan (cat)' },
  { value: 'ceb', label: 'Cebuano (ceb)' },
  { value: 'chr', label: 'Cherokee (chr)' },
  { value: 'chi_sim', label: 'Chinese — Simplified (chi_sim)' },
  { value: 'chi_sim_vert', label: 'Chinese — Simplified, vertical (chi_sim_vert)' },
  { value: 'chi_tra', label: 'Chinese — Traditional (chi_tra)' },
  { value: 'chi_tra_vert', label: 'Chinese — Traditional, vertical (chi_tra_vert)' },
  { value: 'cos', label: 'Corsican (cos)' },
  { value: 'hrv', label: 'Croatian (hrv)' },
  { value: 'ces', label: 'Czech (ces)' },
  { value: 'dan', label: 'Danish (dan)' },
  { value: 'div', label: 'Dhivehi (div)' },
  { value: 'nld', label: 'Dutch (nld)' },
  { value: 'dzo', label: 'Dzongkha (dzo)' },
  { value: 'enm', label: 'English — Middle, 1100–1500 (enm)' },
  { value: 'epo', label: 'Esperanto (epo)' },
  { value: 'est', label: 'Estonian (est)' },
  { value: 'fao', label: 'Faroese (fao)' },
  { value: 'fil', label: 'Filipino (fil)' },
  { value: 'fin', label: 'Finnish (fin)' },
  { value: 'fra', label: 'French (fra)' },
  { value: 'frm', label: 'French — Middle, 1400–1600 (frm)' },
  { value: 'fry', label: 'Frisian — Western (fry)' },
  { value: 'glg', label: 'Galician (glg)' },
  { value: 'kat', label: 'Georgian (kat)' },
  { value: 'kat_old', label: 'Georgian — old (kat_old)' },
  { value: 'deu', label: 'German (deu)' },
  { value: 'deu_latf', label: 'German — Fraktur (deu_latf)' },
  { value: 'frk', label: 'German — Frankish, legacy (frk)' },
  { value: 'ell', label: 'Greek (ell)' },
  { value: 'guj', label: 'Gujarati (guj)' },
  { value: 'hat', label: 'Haitian Creole (hat)' },
  { value: 'heb', label: 'Hebrew (heb)' },
  { value: 'hin', label: 'Hindi (hin)' },
  { value: 'hun', label: 'Hungarian (hun)' },
  { value: 'isl', label: 'Icelandic (isl)' },
  { value: 'ind', label: 'Indonesian (ind)' },
  { value: 'iku', label: 'Inuktitut (iku)' },
  { value: 'gle', label: 'Irish (gle)' },
  { value: 'ita', label: 'Italian (ita)' },
  { value: 'ita_old', label: 'Italian — old (ita_old)' },
  { value: 'jpn', label: 'Japanese (jpn)' },
  { value: 'jpn_vert', label: 'Japanese — vertical (jpn_vert)' },
  { value: 'jav', label: 'Javanese (jav)' },
  { value: 'kan', label: 'Kannada (kan)' },
  { value: 'kaz', label: 'Kazakh (kaz)' },
  { value: 'khm', label: 'Khmer (khm)' },
  { value: 'kor', label: 'Korean (kor)' },
  { value: 'kor_vert', label: 'Korean — vertical (kor_vert)' },
  { value: 'kmr', label: 'Kurdish — Northern, Kurmanji (kmr)' },
  { value: 'kir', label: 'Kyrgyz (kir)' },
  { value: 'lao', label: 'Lao (lao)' },
  { value: 'lat', label: 'Latin (lat)' },
  { value: 'lav', label: 'Latvian (lav)' },
  { value: 'lit', label: 'Lithuanian (lit)' },
  { value: 'ltz', label: 'Luxembourgish (ltz)' },
  { value: 'mkd', label: 'Macedonian (mkd)' },
  { value: 'msa', label: 'Malay (msa)' },
  { value: 'mal', label: 'Malayalam (mal)' },
  { value: 'mlt', label: 'Maltese (mlt)' },
  { value: 'mri', label: 'Maori (mri)' },
  { value: 'mar', label: 'Marathi (mar)' },
  { value: 'equ', label: 'Math / equation detection (equ)' },
  { value: 'mon', label: 'Mongolian (mon)' },
  { value: 'nep', label: 'Nepali (nep)' },
  { value: 'nor', label: 'Norwegian (nor)' },
  { value: 'oci', label: 'Occitan — post-1500 (oci)' },
  { value: 'ori', label: 'Odia (ori)' },
  { value: 'osd', label: 'Orientation/script detection (osd)' },
  { value: 'pus', label: 'Pashto (pus)' },
  { value: 'fas', label: 'Persian (fas)' },
  { value: 'pol', label: 'Polish (pol)' },
  { value: 'por', label: 'Portuguese (por)' },
  { value: 'pan', label: 'Punjabi (pan)' },
  { value: 'que', label: 'Quechua (que)' },
  { value: 'ron', label: 'Romanian (ron)' },
  { value: 'rus', label: 'Russian (rus)' },
  { value: 'san', label: 'Sanskrit (san)' },
  { value: 'gla', label: 'Scottish Gaelic (gla)' },
  { value: 'srp', label: 'Serbian (srp)' },
  { value: 'srp_latn', label: 'Serbian — Latin (srp_latn)' },
  { value: 'snd', label: 'Sindhi (snd)' },
  { value: 'sin', label: 'Sinhala (sin)' },
  { value: 'slk', label: 'Slovak (slk)' },
  { value: 'slv', label: 'Slovenian (slv)' },
  { value: 'spa', label: 'Spanish (spa)' },
  { value: 'spa_old', label: 'Spanish — old (spa_old)' },
  { value: 'sun', label: 'Sundanese (sun)' },
  { value: 'swa', label: 'Swahili (swa)' },
  { value: 'swe', label: 'Swedish (swe)' },
  { value: 'syr', label: 'Syriac (syr)' },
  { value: 'tgk', label: 'Tajik (tgk)' },
  { value: 'tam', label: 'Tamil (tam)' },
  { value: 'tat', label: 'Tatar (tat)' },
  { value: 'tel', label: 'Telugu (tel)' },
  { value: 'tha', label: 'Thai (tha)' },
  { value: 'bod', label: 'Tibetan (bod)' },
  { value: 'tir', label: 'Tigrinya (tir)' },
  { value: 'ton', label: 'Tongan (ton)' },
  { value: 'tur', label: 'Turkish (tur)' },
  { value: 'ukr', label: 'Ukrainian (ukr)' },
  { value: 'urd', label: 'Urdu (urd)' },
  { value: 'uig', label: 'Uyghur (uig)' },
  { value: 'uzb', label: 'Uzbek (uzb)' },
  { value: 'uzb_cyrl', label: 'Uzbek — Cyrillic (uzb_cyrl)' },
  { value: 'vie', label: 'Vietnamese (vie)' },
  { value: 'cym', label: 'Welsh (cym)' },
  { value: 'yid', label: 'Yiddish (yid)' },
  { value: 'yor', label: 'Yoruba (yor)' },
];
