// AUTO-GENERATED from docs/data/tool-review-chain-suggestions-2026-07-11.json
// (phase-1 tool review). Curated 'what would a user plausibly do next'
// lists, filtered to MIME-legal edges; JSON-report tools with no legal
// semantic hop fall back to the generic JSON utilities. A tool's own
// inline chainSuggestions takes precedence; regenerate, don't hand-edit.

export const CURATED_CHAIN_SUGGESTIONS: Record<string, readonly string[]> = {
  "analyze-loudness": ["json-formatter", "json-yaml", "json-flatten"],
  "api-key-format": ["hash"],
  "backup-codes": ["base32", "base64"],
  "barcode": ["svg-to-png"],
  "base32": ["base64", "case-converter", "text-diff", "word-counter"],
  "base58": ["hash", "base32", "text-escape", "url-encoder"],
  "base64": ["hash", "hmac", "file-fingerprint", "text-escape"],
  "bg-remove": ["face-blur", "compress", "convert", "resize", "strip-exif"],
  "burn-subtitles": ["compress-video", "trim-media", "resize-video", "extract-audio", "video-to-gif"],
  "calculator": ["json-formatter"],
  "case-converter": ["slug", "text-escape", "url-encoder", "word-counter"],
  "color-blind-simulator": ["image-info", "compress", "color-palette", "image-diff", "detect-objects"],
  "color-contrast": ["json-formatter", "json-yaml", "json-flatten"],
  "color-converter": ["json-formatter", "json-yaml", "json-flatten"],
  "color-harmony": ["json-formatter"],
  "color-palette": ["json-formatter", "json-yaml", "json-flatten"],
  "compound-interest": ["json-formatter", "json-yaml", "text-template"],
  "compress": ["convert", "resize", "crop", "image-info", "strip-exif"],
  "compress-video": ["trim-media", "resize-video", "extract-audio", "video-to-gif", "mute-video"],
  "convert": ["resize", "crop", "compress", "strip-exif", "image-to-pdf"],
  "convert-audio": ["trim-media", "audio-enhance", "transcribe", "normalize-loudness", "analyze-loudness"],
  "convert-geo": ["zip-create"],
  "convert-subtitles": ["text-summarize", "text-translate", "word-counter", "text-stats", "text-keywords"],
  "convert-video": ["compress-video", "trim-media", "resize-video", "extract-audio", "video-to-gif"],
  "cron-from-text": ["json-formatter", "json-yaml", "json-flatten"],
  "cron-parser": ["json-formatter", "json-yaml", "json-flatten"],
  "crop": ["resize", "compress", "image-watermark"],
  "crop-video": ["letterbox-video", "fade-video", "video-speed", "compress-video"],
  "css-formatter": ["css-minify"],
  "css-minify": ["css-formatter"],
  "csv-deduplicate": ["csv-merge", "csv-sort", "csv-filter"],
  "csv-diff": ["json-formatter", "json-yaml", "json-flatten"],
  "csv-filter": ["csv-sort", "csv-deduplicate", "csv-info", "csv-to-excel", "csv-merge"],
  "csv-info": ["json-formatter", "json-yaml", "json-flatten"],
  "csv-json": ["json-formatter", "number-base-converter", "token-count"],
  "csv-merge": ["csv-filter", "csv-deduplicate", "csv-to-json-schema", "csv-json", "csv-info"],
  "csv-sort": ["csv-filter", "csv-deduplicate", "csv-info", "csv-to-excel", "csv-merge"],
  "csv-template": ["zip-extract", "zip-info", "zip-remove"],
  "csv-to-excel": ["merge-workbooks", "excel-to-csv", "excel-to-json", "excel-info", "split-sheets"],
  "csv-to-geojson": ["convert-geo", "geojson-to-kml"],
  "csv-to-json-schema": ["json-schema-validate", "json-formatter", "json-yaml", "json-diff"],
  "date-calculator": ["json-formatter"],
  "diff-apply": ["text-diff", "csv-json", "json-diff", "case-converter"],
  "excel-info": ["csv-sql"],
  "excel-to-csv": ["csv-to-geojson", "csv-merge", "csv-deduplicate", "csv-sort", "csv-filter"],
  "excel-to-json": ["json-formatter", "json-to-excel", "json-flatten", "json-schema-infer"],
  "extract-audio": ["trim-media", "audio-enhance", "transcribe", "normalize-loudness", "analyze-loudness"],
  "extract-frame": ["compress", "convert", "image-info", "crop", "resize"],
  "face-blur": ["bg-remove", "compress", "convert", "resize", "strip-exif"],
  "fade-video": ["vignette-video", "letterbox-video", "compress-video", "reverse-video"],
  "favicon": ["zip-info", "zip-flatten", "zip-remove"],
  "favicon-from-url": ["json-formatter", "json-yaml", "json-flatten"],
  "file-fingerprint": ["mime-detect", "hash", "base64"],
  "flip-image": ["compress", "convert", "rotate-image"],
  "frontmatter-to-csv": ["csv-to-excel", "csv-merge", "csv-deduplicate", "csv-filter"],
  "geojson-to-kml": ["convert-geo", "kml-to-geojson"],
  "gpx-to-geojson": ["convert-geo", "geojson-to-kml"],
  "gpx-to-kml": ["convert-geo", "kml-to-geojson"],
  "grayscale": ["compress", "convert", "image-watermark"],
  "hash": ["hmac", "file-fingerprint", "pgp-sign"],
  "hmac": ["hash", "pgp-sign", "pgp-verify", "webhook-verify"],
  "hotp-code": ["json-formatter", "json-yaml", "json-flatten"],
  "html-clean": ["text-stats-by-paragraph", "word-counter", "text-diff"],
  "html-extract-links": ["csv-json", "json-formatter"],
  "html-formatter": ["html-minify", "html-to-markdown", "extract-article-text"],
  "html-minify": ["html-formatter", "extract-article-text", "html-to-pdf"],
  "html-redact": ["html-to-markdown", "html-minify", "html-formatter", "html-clean"],
  "html-to-markdown": ["text-summarize", "text-translate", "text-sentences", "text-keywords", "text-readability"],
  "html-to-pdf": ["pdf-to-text", "merge-pdf", "pdf-compress", "pdf-encrypt", "pdf-info"],
  "image-diff": ["compress", "convert", "image-info"],
  "image-info": ["json-formatter", "json-yaml", "json-flatten"],
  "image-similarity": ["json-formatter", "json-yaml", "json-flatten"],
  "image-to-ascii": ["text-diff", "hash", "url-encoder", "text-escape", "base58"],
  "image-to-pdf": ["merge-pdf", "pdf-to-text", "pdf-summarize", "pdf-compress"],
  "image-watermark": ["compress", "convert", "strip-exif"],
  "invert": ["compress", "convert", "image-watermark"],
  "investment-dca": ["json-formatter", "json-yaml", "text-template"],
  "json-diff": ["json-formatter", "json-schema-validate"],
  "json-flatten": ["json-unflatten", "json-formatter", "json-diff"],
  "json-formatter": ["json-diff", "json-flatten", "json-schema-validate", "json-schema-infer", "json-yaml"],
  "json-merge": ["json-diff", "json-formatter", "csv-json", "json-flatten"],
  "json-path": ["json-formatter", "json-yaml", "json-flatten"],
  "json-schema-infer": ["json-formatter", "json-yaml", "json-flatten"],
  "json-schema-validate": ["json-formatter", "json-schema-infer", "json-yaml"],
  "json-to-excel": ["excel-to-csv", "excel-info", "merge-workbooks", "split-sheets"],
  "json-to-xml": ["xml-to-json", "xml-formatter"],
  "json-unflatten": ["json-flatten", "json-formatter", "json-diff"],
  "json-yaml": ["json-formatter", "csv-json", "json-merge", "number-base-converter"],
  "jwt-decoder": ["json-formatter", "base64", "hash"],
  "jwt-sign": ["json-schema-validate", "base64"],
  "kml-to-geojson": ["convert-geo", "geojson-to-kml"],
  "letterbox-video": ["crop-video", "compress-video", "video-add-text", "fade-video"],
  "license-key": ["hash"],
  "lorem-ipsum": ["word-counter", "text-stats", "markdown-to-html", "text-sentences"],
  "markdown-frontmatter": ["json-formatter", "json-yaml", "json-flatten"],
  "markdown-to-html": ["html-to-pdf", "html-to-markdown", "html-formatter", "html-clean", "html-extract-links"],
  "merge-pdf": ["pdf-to-text", "pdf-compress", "pdf-encrypt", "pdf-info", "reorder-pdf"],
  "merge-workbooks": ["excel-to-csv", "split-sheets", "excel-info"],
  "mime-detect": ["hash", "file-fingerprint", "base64"],
  "mix-audio": ["trim-media", "compress-video", "video-volume", "normalize-loudness"],
  "morse-code": ["case-converter", "text-stats", "text-diff", "slug"],
  "number-base-converter": ["json-formatter", "json-yaml", "json-flatten"],
  "ocr": ["text-summarize", "text-translate", "text-sentiment", "text-stats"],
  "ocr-pro": ["text-to-speech-pro", "base64", "hash", "word-counter", "text-redact"],
  "ocr-suspicious": ["json-formatter", "json-yaml", "json-flatten"],
  "openapi-validate": ["json-formatter", "json-yaml", "json-flatten"],
  "otpauth-uri": ["json-formatter", "json-yaml", "json-flatten"],
  "package-json-validate": ["json-formatter", "json-yaml", "json-flatten"],
  "page-numbers-pdf": ["pdf-to-text", "pdf-compress", "pdf-encrypt", "pdf-info", "split-pdf"],
  "password-generator": ["hash"],
  "password-strength": ["hash"],
  "pdf-compress": ["pdf-encrypt", "pdf-info", "pdf-to-image", "merge-pdf", "pdf-to-text"],
  "pdf-crop": ["pdf-compress", "merge-pdf", "reorder-pdf"],
  "pdf-decrypt": ["pdf-encrypt", "pdf-compress", "pdf-info", "pdf-to-text", "merge-pdf"],
  "pdf-delete-pages": ["pdf-compress", "reorder-pdf", "rotate-pdf"],
  "pdf-encrypt": ["pdf-compress", "pdf-decrypt", "pdf-info", "watermark-pdf", "rotate-pdf"],
  "pdf-extract-data": ["csv-sql"],
  "pdf-extract-images": ["zip-extract"],
  "pdf-extract-pages": ["merge-pdf", "pdf-compress", "reorder-pdf"],
  "pdf-extract-tables": ["json-path", "json-to-xml", "csv-json", "json-flatten"],
  "pdf-info": ["json-formatter", "json-yaml", "json-flatten"],
  "pdf-metadata": ["pdf-compress", "merge-pdf", "pdf-encrypt"],
  "pdf-redact": ["pdf-compress", "merge-pdf", "reorder-pdf"],
  "pdf-suspicious": ["json-formatter", "json-yaml", "json-flatten"],
  "pdf-to-text": ["text-summarize", "text-translate", "text-sentiment", "text-stats"],
  "percentage-calculator": ["json-formatter"],
  "pgp-armor": ["hash", "url-encoder", "base58"],
  "pgp-decrypt": ["hash", "base64", "pgp-verify", "pgp-armor", "hmac"],
  "pgp-encrypt": ["pgp-sign", "pgp-armor", "hash", "base64", "hmac"],
  "pgp-sign": ["pgp-verify", "hash", "base64", "pgp-armor", "hmac"],
  "pgp-verify": ["json-formatter", "hash", "hmac", "pgp-encrypt"],
  "prompt-injection-demo": ["json-formatter", "json-path", "json-schema-validate", "hash", "hmac"],
  "qr": ["convert", "resize", "image-info", "qr-reader"],
  "qr-reader": ["json-formatter", "json-yaml", "json-flatten"],
  "regex-explain": ["json-formatter", "json-yaml", "json-flatten"],
  "regex-from-text": ["json-formatter", "json-yaml", "json-flatten"],
  "regex-tester": ["json-formatter", "json-yaml", "json-flatten"],
  "reorder-pdf": ["pdf-to-text", "pdf-compress", "pdf-encrypt", "pdf-info", "pdf-flatten"],
  "replace-audio": ["trim-media", "compress-video", "convert-video", "burn-subtitles"],
  "resize": ["compress", "convert", "image-watermark"],
  "resize-video": ["compress-video", "trim-media", "extract-audio", "mute-video", "video-to-gif"],
  "reverse-video": ["fade-video", "loop-video", "video-speed", "video-add-text"],
  "roman-numeral": ["json-formatter", "json-diff", "json-merge"],
  "rotate-image": ["compress", "strip-exif", "convert"],
  "rotate-pdf": ["pdf-to-text", "pdf-compress", "pdf-encrypt", "pdf-info", "reorder-pdf"],
  "rotate-video": ["compress-video", "trim-media", "resize-video", "extract-audio", "mute-video"],
  "sepia": ["compress", "convert", "image-watermark"],
  "shapefile-to-geojson": ["convert-geo", "geojson-to-kml"],
  "signed-cookie-decode": ["json-formatter", "json-yaml", "json-flatten"],
  "signed-url": ["json-formatter", "json-yaml", "json-flatten"],
  "slug": ["url-encoder", "case-converter", "hash", "text-diff"],
  "split-pdf": ["merge-pdf", "pdf-compress", "pdf-encrypt", "pdf-info", "reorder-pdf"],
  "split-sheets": ["zip-extract", "zip-info", "zip-flatten"],
  "sql-format-explain": ["json-formatter"],
  "sql-formatter": ["sql-format-explain", "json-formatter"],
  "strip-exif": ["compress", "convert", "face-blur", "bg-remove", "resize"],
  "svg-optimizer": ["svg-to-png"],
  "svg-to-png": ["resize", "compress", "color-palette", "image-info", "rotate-image"],
  "text-confusable": ["json-formatter", "json-yaml", "json-flatten"],
  "text-diff": ["diff-apply", "json-diff", "text-diff-levenshtein"],
  "text-diff-levenshtein": ["json-formatter", "json-yaml", "json-flatten"],
  "text-embed": ["json-formatter", "json-yaml", "json-flatten"],
  "text-escape": ["case-converter", "url-encoder", "base64"],
  "text-frequency": ["json-formatter", "json-yaml", "json-flatten"],
  "text-ner": ["json-formatter", "json-yaml", "json-flatten"],
  "text-readability": ["json-formatter", "json-yaml", "json-flatten"],
  "text-redact": ["text-summarize", "text-translate", "prompt-injection-demo", "text-sentiment", "text-diff"],
  "text-sentiment": ["json-formatter", "json-yaml", "json-flatten"],
  "text-stats": ["json-formatter", "json-yaml", "json-flatten"],
  "text-stats-by-paragraph": ["csv-json", "json-formatter"],
  "text-summarize": ["text-translate", "text-sentences", "text-keywords", "text-sentiment", "text-readability"],
  "text-suspicious": ["json-formatter", "json-yaml", "json-flatten"],
  "text-template": ["case-converter", "slug", "text-stats-by-paragraph"],
  "text-translate": ["text-translate-pro", "text-summarize", "text-sentences", "text-readability", "text-ner-pro"],
  "timestamp-converter": ["json-formatter", "json-yaml", "json-flatten"],
  "token-count": ["json-formatter", "json-yaml", "json-flatten"],
  "totp-code": ["json-formatter", "json-yaml", "json-flatten"],
  "unicode-info": ["json-formatter", "json-yaml", "json-flatten"],
  "unicode-normalize": ["text-stats", "text-dates", "text-ner"],
  "unit-converter": ["json-formatter"],
  "upscale-2x": ["compress", "convert", "image-info", "grayscale", "image-diff"],
  "url-build": ["hash"],
  "url-encoder": ["slug", "text-escape"],
  "url-parse": ["json-formatter", "json-yaml", "json-flatten"],
  "url-shorten-local": ["hash"],
  "uuid-generator": ["hash", "base64", "case-converter"],
  "video-add-text": ["compress-video", "trim-media", "resize-video", "video-to-gif", "extract-audio"],
  "video-color-correct": ["compress-video", "trim-media", "resize-video", "video-to-gif", "extract-audio"],
  "video-concat": ["compress-video", "trim-media", "resize-video", "extract-audio", "video-to-gif"],
  "video-crossfade": ["compress-video", "trim-media", "resize-video", "video-to-gif", "extract-audio"],
  "video-overlay-image": ["compress-video", "trim-media", "resize-video", "video-to-gif", "extract-audio"],
  "video-quality-metrics": ["json-formatter", "json-yaml", "json-flatten"],
  "video-side-by-side": ["compress-video", "crop-video", "video-add-text", "fade-video"],
  "video-speed": ["compress-video", "resize-video", "trim-media", "extract-audio", "mute-video"],
  "video-to-gif": ["image-to-ascii"],
  "vignette-video": ["fade-video", "letterbox-video", "video-color-correct", "compress-video"],
  "watermark-pdf": ["pdf-to-text", "pdf-compress", "pdf-encrypt", "pdf-info", "split-pdf"],
  "webhook-replay": ["webhook-verify", "hash", "base64"],
  "webhook-verify": ["webhook-replay", "hmac", "hash"],
  "word-counter": ["json-formatter", "json-yaml", "json-flatten"],
  "xml-formatter": ["xml-to-json"],
  "xml-to-json": ["json-to-xml", "json-formatter", "json-diff", "json-yaml"],
  "yaml-validate": ["json-formatter", "json-yaml", "json-flatten"],
  "zip-create": ["zip-extract", "zip-info"],
  "zip-extract": ["zip-create"],
  "zip-info": ["json-formatter", "json-yaml", "json-flatten"],
};
